FROM custom/sdr-apps

ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN cd && \
   git clone https://github.com/DIFI-Consortium/gr-difi.git && \
   cd gr-difi && \
   mkdir build && \
   cd build && \
   cmake -DCMAKE_INSTALL_PREFIX=/usr .. && \
   make clean && \
   make -j8 install


RUN cd && \
   git clone https://github.com/radioconda/gr-inspector.git && \
   cd gr-inspector && \
   mkdir build && \
   cd build && \
   cmake -DCMAKE_INSTALL_PREFIX=/usr .. && \
   make clean && \
   make -j8 install


RUN cd && \
    git clone https://github.com/tapparelj/gr-lora_sdr.git && \
    cd gr-lora_sdr && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr .. && \
    make clean && \
    make -j8 install

RUN cd && \
   git clone https://github.com/daniestevez/gr-satellites.git && \
   cd gr-satellites && \
   git checkout maint-3.10 && \
   mkdir build && \
   cd build && \
   cmake -DCMAKE_INSTALL_PREFIX=/usr .. && \
   make clean && \
   make -j8 install


RUN cd && \
   git clone https://github.com/karel/gr-adapt.git && \
   cd gr-adapt && \
   mkdir build && \
   cd build && \
   cmake -DCMAKE_INSTALL_PREFIX=/usr .. && \
   make clean && \
   make -j8 install


RUN userdel -r ubuntu
RUN mkdir /home/gnuradio
RUN useradd --uid 1000 -m gnuradio -d /home/gnuradio
RUN chown -R gnuradio /home/gnuradio

RUN apt-get clean

USER gnuradio

