FROM custom/sdr-ubuntu-base:latest

ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN apt update

#install hackrf
RUN apt install -y hackrf libhackrf-dev libhackrf0

RUN apt install -y gnuradio gnuradio-dev

RUN apt install -y gr-fosphor gr-rds gr-air-modes gr-limesdr gr-radar gr-radar-doc gr-limesdr gr-hpsdr gr-gsm gr-funcube

RUN apt install -y gnss-sdr

# TODO: Pulls in xorg. 
# RUN apt install -y cubicsdr

RUN apt install -y gqrx-sdr

RUN apt install -y libsoapysdr0.8 libsoapysdr-dev libsoapysdr-doc soapysdr-module-hackrf \
                   soapysdr-module-osmosdr soapysdr-module-rtlsdr soapysdr-tools


# Add build-dependencies.
RUN apt install -y libsndfile1-dev

RUN apt-get clean

