FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN apt update

RUN apt install -y software-properties-common

RUN add-apt-repository ppa:gnuradio/gnuradio-releases-3.8

# Force x-libs to be included without xorg.
RUN apt-get install -y --no-install-recommends xterm

RUN apt install -y libcppunit-dev

#install nano
RUN apt install -y nano

#install snap
RUN apt install -y geany

#install git & compiler requirements.
RUN apt install -y git build-essential

RUN apt install -y cmake libboost-all-dev swig liborc-dev python3-sphinx doxygen libsdl1.2-dev \
                   libgsl-dev libqwt-qt5-dev libqt5opengl5-dev libzmq3-dev gobject-introspection \
                   gir1.2-gtk-3.0 xterm pybind11-dev


